#!/bin/bash

# Changes the scoreboard IP in the viruses
# TODO: Use a regex instead of leaving x.x.x.x as a placeholder in the viruses

sed -r -i "s/\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}/$1/g" alex/GLaDOS/GLaDOS.c
sed -r -i "s/\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}/$1/g" david/virus.rs
sed -r -i "s/\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}/$1/g" michael/cat
sed -r -i "s/\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}/$1/g" isaac/listener.py
sed -r -i "s/\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}\.\b[0-9]{1,3}/$1/g" victor/\[systemdeamond\]
