#!/usr/bin/python

# This script simply creates a file in the root directory if it is not already there.
# It is spawned by the [systemdeamond] process/virus, which restarts it if it is killed.

import os
from time import sleep

while 1:
    groot = """
    I'm still here :)
    
         .^. .  _        
        /: ||`\/ \~  ,        
      , [   &    / \ y'   
     {v':   `\   / `&~-,  
    'y. '    |`   .  ' /   
     \   '  .       , y   
     v .        '     v   
     V  .~.      .~.  V   
     : (  0)    (  0) :   
      i `'`      `'` j          
       i    \__/    ,j           
        `%`~....~'&            
     <~o' /  \/` \-s,         
      o.~'.  )(  r  .o ,.  
     o',  %``\/``& : 'bF  
    d', ,ri.~~-~.ri , +h  
    `oso' d`~..~`b 'sos`  
         d`+ II +`b       
         i_:_yi_;_y   
    
    """
    
    cmd = "cat << 'EOF' > /root/imstillhere\n" + groot
    
    os.system(cmd)
    sleep(15)
